# name: boost
# desc: Set up Laravel Boost (AI guidelines, agent skills, MCP server)
# default: on
#
# Boost publishes guidelines and skills tailored to the packages the project
# actually has, and registers an MCP server the coding agent can query for the
# app's schema, logs and docs. It is installed as a dev dep by the dev-deps
# module; this step is what actually publishes its resources.
#
# Which features get published is a knob, not a constant:
#   SETUP_BOOST_FEATURES="--guidelines --skills"   # e.g. no MCP registration
FEATURES="${SETUP_BOOST_FEATURES:---guidelines --skills --mcp}"

if ! artisan_has 'boost:install'; then
    info "laravel/boost is not installed — skipping (add it to assets/dev-packages.txt to enable)."
    return 0 2>/dev/null || exit 0
fi

# `boost:install` is used rather than `boost:update` even on a project that
# already has Boost. Installing is idempotent — it re-syncs guidelines and
# skills against the current composer.json — while `boost:update` refuses to run
# unless boost.json carries an agent list, which a non-interactive install does
# not write. Install covers both cases; update only covers one.
info "publishing Boost resources ($FEATURES)..."
run $ARTISAN_CMD boost:install $FEATURES --no-interaction

# `.mcp.json` records absolute interpreter and project paths (on WSL, even a
# `wsl.exe` invocation), so it is valid only on the machine that generated it.
# `boost.json` is regenerated by every install. Committing either one hands
# teammates a broken MCP server, so keep both out of the repository.
ensure_gitignore '.mcp.json' 'Laravel Boost — machine-specific, regenerated by boost:install'
ensure_gitignore 'boost.json'
